mtitle: "Andrea Graziano"
author: "Andrea Graziano"
description: "personal website"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "CV.md", title: "CV", sidebaricon: address-card}
  - {title: "Co-de-iT", url: "https://www.co-de-it.com"}
  - {file: "blog.md", title: "Blog", sidebaricon: address-card}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:arch.a.graziano@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/digitag1971"}
  - {title: Instagram, icon: instagram, url: "https://www.instagram.com/arch.a.graziano/"}
  - {title: Facebook, icon: e-mail, url: "https://www.facebook.com/arch.a.graziano"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
